### ISSUE TITLE
How to install 

### ISSUE THREAD

**Issue by liyan910117** [ZW-xjtlu/exomePeak2#4]
Hi,
    Recently, i can not install exomePeak2 package because "RMariaDB" package not correct installed, and MySQL and RMySQL also not installed. 
Could you please give some suggestions?

**Comment by ZW-xjtlu** [comment]
> Hi,
> Recently, i can not install exomePeak2 package because "RMariaDB" package not correct installed, and MySQL and RMySQL also not installed.
> Could you please give some suggestions?

Hi Yan,

This is currently an issue for the exomePeak2 package because it depends on RMariaDB instead of suggesting it.
MariaDB is not necessary for most of the major functionalities in exomePeak2. 

Hence, I have made a new commit to the master branch of exomePeak2, changing the relationship to RMariaDB from “depends" to “suggests”. 
Please try to re-install exomePeak2 from directly GitHub with devtools:install_github(“ZW-xjtlu/exomePeak2”).  Afterward, it should not generate the error message you encountered even without installing the RMariaDB package.

Please communicate with me in case there are any further issues.

Best wishes,
Zhen

**Comment by liyan910117** [comment]
thanks for your reply!

**Comment by liyan910117** [comment]
exomePeak2 package has been istalled, thank you!
